"""create tables from models
Revision ID: ae791ce8d898
Revises: 79bc1ced69b2
Create Date: 2026-06-11 11:57:59.382637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae791ce8d898'
down_revision = '79bc1ced69b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('GENERAL', 'URGENT', 'FINANCIAL', 'EVENT', name='announcementtype'), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dues_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('term', sa.String(length=20), nullable=False),
    sa.Column('amount_ghs', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('grace_period_days', sa.Integer(), nullable=True),
    sa.Column('late_fee_ghs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manual_amendments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('manual_payment_id', sa.String(length=36), nullable=False),
    sa.Column('original_values', sa.Text(), nullable=True),
    sa.Column('corrected_values', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('amended_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('amended_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manual_payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('student_index_no', sa.String(length=50), nullable=True),
    sa.Column('student_name', sa.String(length=255), nullable=True),
    sa.Column('parent_phone', sa.String(length=20), nullable=True),
    sa.Column('term', sa.String(length=20), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('amount_ghs', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_mode', sa.Enum('CASH', 'CHEQUE', 'BANK_DEPOSIT', name='manualpaymentmode'), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('recorded_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('recorded_by_name', sa.String(length=255), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sms_sent', sa.Boolean(), nullable=True),
    sa.Column('sms_sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('amendment_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_table('meeting_attendance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meetings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('term', sa.String(length=20), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', name='meetingstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_student_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('match_status', sa.Enum('MATCHED', 'PENDING', name='matchstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('dues_config_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=False),
    sa.Column('amount_ghs', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paystack_reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='paymentstatus'), nullable=True),
    sa.Column('receipt_number', sa.String(length=50), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paystack_reference'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_table('pending_matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=False),
    sa.Column('entered_ward_name', sa.String(length=255), nullable=True),
    sa.Column('entered_ward_form', sa.String(length=50), nullable=True),
    sa.Column('entered_index_number', sa.String(length=50), nullable=True),
    sa.Column('top_candidates', sa.Text(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('recipient_phone', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('index_number', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('form', sa.String(length=50), nullable=True),
    sa.Column('stream', sa.String(length=100), nullable=True),
    sa.Column('parent_phone_1', sa.String(length=20), nullable=True),
    sa.Column('parent_phone_2', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_number')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'FINANCIAL_STAFF', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_first_login', sa.Boolean(), nullable=True),
    sa.Column('totp_secret', sa.String(length=255), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('students')
    op.drop_table('sms_logs')
    op.drop_table('pending_matches')
    op.drop_table('payments')
    op.drop_table('parents')
    op.drop_table('parent_student_links')
    op.drop_table('meetings')
    op.drop_table('meeting_attendance')
    op.drop_table('manual_payments')
    op.drop_table('manual_amendments')
    op.drop_table('job_records')
    op.drop_table('dues_configs')
    op.drop_table('announcements')
    # ### end Alembic commands ###
